### ISSUE TITLE
Remove unread UiColors slots, the Mica backdrop value and a duplicate chrome-material helper

### ISSUE THREAD

**Issue by evilchinesefood** [theaamgroup/PaneFlow#815]
## Trigger

The 2026-09-23 audit found theme slots, helpers, and a backdrop variant that nothing reads. `rg -w` across `src-app/{src,tests,examples}` and `crates/` finds only the definitions, the preset literals, and one test.

## Impact

About 110 to 130 lines removed. Each dead `UiColors` slot costs 8 literal lines: 2 in `model.rs` and 6 in `builtin.rs`. DESIGN.md:277 says `agent_claude`/`agent_codex` color "identity dots and status glyphs", but no code reads them.

## Expected behavior

No user-visible change. A config with `"window_backdrop": "mica"` still loads and renders the same. `Mica` and `Auto` already behave identically: both give `Transparent` and both install the sidebar material.

## Evidence

- `theme/model.rs:540` `tool_card_header_bg`, `:564`/`:566` `vc_word_added`/`vc_word_deleted`, and `:593`/`:595` `agent_claude`/`agent_codex` have no reads.
- `model.rs:562` `vc_modified_background` is read only by a test (`:969`, `:984`).
- DESIGN.md describes these slots at `:272-277`, `:797-800`, and `:1362-1363`.
- `theme/signal.rs:19` `ThemeSignal::generation()` has 0 callers. The field stays, because `publish_theme_generation` reads it.
- `theme/builtin.rs:96` `preset_by_name` and its re-export at `theme/mod.rs:11` have 0 callers.
- `app/constants.rs:70` `WindowBackdropPreference::Mica` (parsed at `:93`, documented at `:61`): no match arm singles it out.
- `paneflow-config/src/schema/config.rs:459` `cockpit_chrome_material_enabled()` is identical to `:449` `macos_chrome_material_enabled()`. Its opaque/off pre-check is already the first term of the callee. It has 6 call sites: `main.rs:2082`, `sessions_sidebar.rs:211`, `diff_sidebar/mod.rs:42`, `settings/chrome.rs:307`, `sidebar/mod.rs:1186`, and `review/rail.rs:256`. Its test is `schema.rs:449-471`.
- `constants.rs:122` `macos_sidebar_material_enabled` is **not** a duplicate. It honors the `PANEFLOW_WINDOW_BACKDROP` env override and ignores the `macos_chrome_material` flag, which `main.rs:3407-3414` passes separately. Keep it, with a doc comment naming it as the install gate.

## Done when

- [ ] Delete the 5 unread fields and their literals.
- [ ] Delete `vc_modified_background` and trim the test, or record why it stays.
- [ ] Update DESIGN.md in the same PR, including the `vc_*_background` row at `:274`. Grep for every deleted name, since the same fact appears in several sections.
- [ ] Delete `generation()`, `preset_by_name`, and the re-export.
- [ ] Delete `Mica`, parse `"mica"` to `Auto`, and fix the comment at `:61`. Add a test for that mapping. `docs/user/configuration/schema.md:98-99` and DESIGN.md:1231 stay accurate.
- [ ] Merge `cockpit_chrome_material_enabled` into `macos_chrome_material_enabled` and fold the test.
- [ ] The six CLAUDE.md gates pass. Diff the test names, not the count.
- [ ] `cargo clippy --workspace -- -D warnings` is clean.

## Related

- Found in the 2026-09-23 dead-code audit.
- The diff dock is being removed in a separate issue, which may leave more `vc_*` slots without readers. Run the grep again after it lands.
- Not in scope: `macos_chrome_material_enabled` ignores `PANEFLOW_WINDOW_BACKDROP`, while window creation honors it.

---
Owner-approved in the 2026-09-23 removal audit. Tracking: #807
